- requirements.txt
add global util module and requirements
> add global util module and requirements

- llm_eval/datasets/__init__.py
- llm_eval/datasets/haerae.py
> add haerae bench dataset

- llm_eval/evaluation/__init__.py
- llm_eval/evaluation/string_match.py
> Add string match evaluator

- llm_eval/models/base.py
- llm_eval/scaling_methods/__init__.py
- llm_eval/scaling_methods/base.py
- llm_eval/scaling_methods/self_consistency.py
- llm_eval/test/test_config.yaml
- llm_eval/test/test_scaling.py
> Add cot and majority voting

- llm_eval/evaluation/string_match.py
string_match를 개선했습니다.
ignore_case: bool = True,
ignore_punctuation: bool = False,
ignore_numbers: bool = False,
regexes_to_ignore: Optional[List[str]] = None,
추가했습니다.
> enhance string_match.py

- llm_eval/models/__init__.py
- llm_eval/models/huggingface.py
> add huggingface model backend

- llm_eval/models/litellm_backend.py
오픈ai,앤트로픽, 배드록, 애저 프로바이더가 작동되게 만들었는데
이게 맞는지 검토 부탁드립니다.
> litellm_backend.py

- .gitignore
- llm_eval/datasets/__init__.py
- llm_eval/models/__init__.py
- llm_eval/models/huggingface.py
- llm_eval/models/openai_backend.py
- llm_eval/runner.py
- llm_eval/test/test_datasets.py
- requirements.txt
> minor bug fix

- .gitignore
- llm_eval/datasets/__init__.py
- llm_eval/datasets/click.py
- llm_eval/datasets/k2_eval.py
- llm_eval/datasets/kmmlu.py
- llm_eval/test/test_config.yaml
- llm_eval/test/test_datasets.py
- requirements.txt
- EunsuKim/CLIcK 데이터셋을 추가하였습니다.
- 
- 
- pytest -m llm_eval/test/test_datasets.py를 실행하십시오.
- 기존 test_datasets은 split를 'test'로 상정하였지만, CLIcK의 경우 split 옵션이 'train'뿐이어서 에러가 발생하였습니다.
-  test_config.yaml datasets에 key, split 두 가지 옵션을 받을 수 있도록 수정하여 해결하였습니다.
- 만약 split 옵션이 따로 입력되지 않으면 default는 'test'입니다.
Closes #50
> feat: click dataset 추가

- llm_eval/evaluation/llm_judge.py
- llm_eval/evaluation/test_llm_judge.py
- llm_eval/models/huggingface.py
- llm_eval/models/multi.py
- llm_eval/models/openai_backend.py
- llm_eval/utils/prompt_template.py
지금 단일모델만 가지고 평가 테스트만 해본 상태입니다.
내일 오전 까지 고도화 해서 다시 올리도록 하겠습니다.
test_llm_judge 실행했을 때 답변 저렇게 나오면 되는지 확인만 우선 부탁드립니다. 
감사합니다.
데이터 연결, 모델 여러개 정도 추가 부분 추가로 작성하려고 합니다 .
> llm_as_a_judge 테스트

- llm_eval/datasets/click.py
- llm_eval/datasets/kmmlu.py
- llm_eval/evaluation/string_match.py
- llm_eval/utils/prompt_template.py
> enhance string match for cot

- llm_eval/models/openai_backend.py
@h-albert-lee 
기존 openai_backend.py에 VLM 입력 처리를 위한 API 지원 기능을 추가했습니다!
리뷰 요청드립니다. 🙇🏻‍♀️
> Feat: enhance OpenAI API for VLM input support

- llm_eval/datasets/hrm8k.py
- llm_eval/evaluation/math_eval.py
- requirements.txt
1. added "put your final answer within \\boxed{}."" for HRM8K questions. this makes parsing easier for math eval
2. add math_eval.py for math evaluations using math-verify from HF.
> update eval for HRM8K

- llm_eval/scaling_methods/self_consistency.py
enhance self-consistency voting
> enhance self-consistency voting

- llm_eval/models/openai_backend.py
@h-albert-lee 
금번 회의 때 말씀하셨던 Arguments 부분 추가해보았습니다. 
그리고 최근 작업한 놋북에서 깃헙 계정 연결이 되어 있지 않더라고요..! 확인감사합니당
> docs: add docstring for OpenAI Vision API implementation

- README.md
- llm_eval/evaluator.py
- llm_eval/runner.py
> enhance api (evaluator and runner) and fix readme

- README.md
- llm_eval/datasets/__init__.py
- llm_eval/datasets/base.py
- llm_eval/datasets/click.py
- llm_eval/datasets/haerae.py
- llm_eval/datasets/hrm8k.py
- llm_eval/datasets/k2_eval.py
- llm_eval/datasets/kmmlu.py
- llm_eval/evaluation/__init__.py
- llm_eval/evaluation/llm_judge.py
- llm_eval/evaluation/math_eval.py
- llm_eval/evaluation/string_match.py
- llm_eval/models/__init__.py
- llm_eval/models/huggingface_backend.py
- llm_eval/models/huggingface_judge.py
- llm_eval/models/huggingface_reward.py
- llm_eval/models/litellm_backend.py
- llm_eval/models/multi.py
- llm_eval/models/openai_backend.py
- llm_eval/scaling_methods/__init__.py
- llm_eval/scaling_methods/base.py
- llm_eval/scaling_methods/best_of_n.py
- llm_eval/scaling_methods/self_consistency.py
- llm_eval/utils/logging.py
- llm_eval/utils/metrics.py
- llm_eval/utils/util.py
- requirements.txt
fix annotations and add loggers
> fix annotations and add loggers

- .github/ISSUE_TEMPLATE/bug_report.md
> add bug template

- llm_eval/models/base.py
- llm_eval/models/huggingface_backend.py
- llm_eval/models/litellm_backend.py
- llm_eval/models/openai_backend.py
- requirements.txt
generate_batch 옵션으로 until 로 옵션 추가
huggingface_backend.py
litellm_backend.py
opeai_backend.py
base.py 
수정
> fix generate_untill in generate_batch

- llm_eval/models/huggingface_backend.py
bugfix: batch_size and padding-left issue
> bugfix: batch_size and padding-left issue

- pyproject.toml
> minor enhancement

- llm_eval/models/huggingface_backend.py
- llm_eval/models/litellm_backend.py
- llm_eval/models/openai_backend.py
- llm_eval/scaling_methods/best_of_n.py
- llm_eval/scaling_methods/self_consistency.py
> fix progress bar

- llm_eval/models/huggingface_backend.py
- llm_eval/models/litellm_backend.py
> fix minor issues

- llm_eval/evaluation/__init__.py
- llm_eval/models/__init__.py
- llm_eval/runner.py
> fix minor bugs

- llm_eval/evaluation/llm_judge.py
- llm_eval/models/huggingface_judge.py
> enhance llm as judge

- llm_eval/datasets/haerae.py
- llm_eval/evaluation/llm_judge.py
- llm_eval/models/huggingface_backend.py
> minor fixes

- llm_eval/models/huggingface_backend.py
- llm_eval/utils/prompt_template.py
> fix cot parser

- llm_eval/evaluation/__init__.py
- llm_eval/evaluation/partial_match.py
> add partial match

- llm_eval/evaluator.py
- llm_eval/runner.py
- requirements.txt
enhance runner/evaluator to handle language penalizer
> enhance runner/evaluator to handle language penalizer

- llm_eval/models/__init__.py
- llm_eval/models/litellm_backend.py
- llm_eval/models/litellm_judge.py
huggingface backend와 유사하게 동작하도록 (cot/batch inference) 코드를 수정하였으며, llm-as-judge로 구현 가능하도록 litellm_judge를 추가했습니다.
제가 litellm을 별로 사용하지 않아봐서, @sangwon1338 한번 검토 부탁드립니다.
> enhance litellm backend and added litellm judge

- llm_eval/scaling_methods/__init__.py
- llm_eval/scaling_methods/beam_search.py
beam search 개선
각 샘플마다 여러 빔을 초기화한 후, 반복적으로 한 토큰씩 생성하여 빔의 텍스트와 점수를 누적->
매 반복마다 동일한 텍스트를 가진 빔은 중복 제거되고, 종료 조건을 만족하면 해당 빔은 완료 처리->
모든 완료된 빔이나 남은 빔 중에서 집계된 점수가 가장 높은 빔의 텍스트를 최종 예측으로 선택
> enhanced beam search

- llm_eval/scaling_methods/beam_search.py
- llm_eval/scaling_methods/best_of_n.py
> minor fixs

- llm_eval/evaluation/partial_match.py
add mcqa option in partial match
> add mcqa option in partial match

- llm_eval/evaluation/__init__.py
- llm_eval/evaluation/log_prob.py
- llm_eval/models/huggingface_backend.py
add log prob evaluation + huggingface backend support
> add log prob evaluation + huggingface backend support

- llm_eval/evaluator.py
- llm_eval/models/huggingface_backend.py
- llm_eval/runner.py
- llm_eval/utils/util.py
> add arg (custom parser)

- tutorial/kor/01-quick-start.md
안녕하세요. 사소한 오타 발견하여 수정하여 올립니다. 
좋은 오픈소스 공유주셔서 감사합니다!
> fix typo in 01-quick-start.md

- llm_eval/models/huggingface_backend.py
- llm_eval/runner.py
- pyproject.toml
- requirements.txt
- add distributed inference (device = "map")
> add distributed inference

- docs/kor/01-quick-start.md
- llm_eval/analysis.py
- llm_eval/utils/util.py
- pyproject.toml
- requirements.txt
add analysis report for result analysis
> add analysis report for result analysis
